CREATE SCHEMA dictionaries;
CREATE SCHEMA lookup;

CREATE TABLE dictionaries.genders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genders text NOT NULL
    );
INSERT INTO dictionaries.genders (genders) 
    VALUES ('Male'),('Female'),('Other'),('Anonymous');  

CREATE TABLE dictionaries.roles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role text NOT NULL,
    description text NOT NULL
    );
INSERT INTO dictionaries.roles (role,description) 
    VALUES ('Superadmin','Ability to directly modify database'),('Admin','Limited ability to modify database'),('Authorizer','Can approve data entries from Enterer role'),('Enterer','Can enter data into the database'),('Student', 'Can enter non-taxonomic data'),('Person','Has no stated privileges');

CREATE TABLE dictionaries.interval_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interval_type text NOT NULL
    );
INSERT INTO dictionaries.interval_types (interval_type) 
    VALUES ('Eon'),('Era'),('Period'),('Epoch'),('Age'),('Zone');

CREATE TABLE dictionaries.zone_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_type text NOT NULL
    );
INSERT INTO dictionaries.zone_types (zone_type) 
    VALUES ('trilobite'),('conodont'),('graptolite'),('foraminifera'),('calcareous nannofossil'),('palynomorph'),('mammalia'),('other');

CREATE TABLE dictionaries.taxonomy_ranks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_rank text NOT NULL
    );
INSERT INTO dictionaries.taxonomy_ranks (taxonomy_rank) 
    VALUES ('subspecies'),('species'),('subgenus'),('genus'),('subtribe'),('tribe'),('subfamily'),('family'),('superfamily'),('infraorder'),('suborder'),('superorder'),('infraclass'),('subclass'),('class'),('superclass'),('subphylum'),('phylum'),('superphylum'),('subkingdom'),('kingdom'),('superkingdom'),('unranked clade'),('unranked');

CREATE TABLE dictionaries.reference_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_type text
    );
INSERT INTO dictionaries.reference_types (reference_type) 
    VALUES ('journal article'),('standalone book'),('edited collection'),('article in edited collection'),('serial monograph'),('unpublished'),('other');

CREATE TABLE dictionaries.book_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_type text
    );
INSERT INTO dictionaries.book_types (book_type) 
    VALUES ('monograph'),('compendium'),('Ph.D. thesis'),('M.S. thesis'),('guidebook');

CREATE TABLE dictionaries.taxonomy_relationships (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_relationship text
    );
INSERT INTO dictionaries.taxonomy_relationships (taxonomy_relationship)
    VALUES ('belongs to'),('subjective synonym of'),('objective synonym of'),('invalid subgroup of'),('misspelling of'),('replaced by'),('nomen dubium'),('nomen nudum'),('nomen oblitum'),('nomen vanum');

CREATE TABLE dictionaries.taxonomy_confidences (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_confidence text,
    taxonomy_confidence_definition text
    );
INSERT INTO dictionaries.taxonomy_confidences (taxonomy_confidence,taxonomy_confidence_definition)
    VALUES ('accepted','An accepted name is a valid name that is not a junior synonym.'),('superseded','A valid name that is a junior synonym.'),('operational','An informal name that can confidently be used as an operational taxonomic unit.'),('tentative','An informal name that is not recommended for general use as an operational taxonomic unit.'),('undocumented','A presumably valid formal name but it is missing a valid authority entry in the database.'),('invalid','A name that is formally considered invalid.');

CREATE TABLE dictionaries.opinion_confidences (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opinion_confidence text,
    opinion_confidence_definition text
    );
INSERT INTO dictionaries.opinion_confidences (opinion_confidence,opinion_confidence_definition)
    VALUES ('stated with evidence', 'Based on a discussion of morphology or a quantitative analysis of relationships'),('stated without evidence','explicitly stated, but without any discussion of morphology or quantitative analysis.'),('implied','not specifically stated, but can be deduced easily from other stated opinions.'),('second hand','no stated evidence, the author does not work on the taxonomic group, and the opinion is based strictly on earlier research by other people.');

CREATE TABLE dictionaries.phylogenetic_statuses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phylogenetic_status text,
    phylogenetic_status_definition text
    );
INSERT INTO dictionaries.phylogenetic_statuses (phylogenetic_status,phylogenetic_status_definition)
    VALUES ('monophyletic','A monophyletic group is a group that includes an ancestor and all of its descendants.'),('paraphyletic','A paraphyletic group is a group that includes an ancestor and some, but not all, of its descendants.'),('polyphyletic','A polyphyletic group is a group that does not include the most recent common ancestor of all members of the group.'),('unknown','The phylogenetic status of the taxon is unknown.');

-- This is a required field for schemas in PBOT, but the current list on PBOT is only applicable to plants
-- Either this requirement needs to go away or a much more expansive and general list needs to be created.
CREATE TABLE dictionaries.parts_preserved (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
INSERT INTO dictionaries.parts_preserved (name)
    VALUES ('root'), ('shoot/axis/wood'), ('leaf'), ('pollen/spore'), ('inflorescence/flower'), ('infructescence/fruit'), ('ovuliferous (seed) cone'), ('staminate (pollen) cone'), ('seed'), ('cuticle'), ('other'), ('unknown');

CREATE TABLE dictionaries.notable_features (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
INSERT INTO dictionaries.notable_features (name)
    VALUES ('cuticle/epidermal features'), ('wood anatomy (secondary growth)'), ('internal anatomy'), ('trace fossils (e.g., insect damage)');

CREATE TABLE persons (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    given_name text NOT NULL,
    family_name text NOT NULL,
    middle text,
    email text,
    password text,
    orcid text,
    role_id integer REFERENCES dictionaries.roles("id") NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- This requires a conditional expression, if the role_id is student or enterer, then it needs an authorizer or above
    gender_id integer REFERENCES dictionaries.genders("id") NOT NULL,
    --country_id integer REFERENCES dictionaries.countries("id") NOT NULL,
    country_code text,
    institution text,
    active boolean,
    total_hours numeric
);
    
 CREATE TABLE refs (
     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --This is the id of the reference record. It will be unique for each version of the reference.
     permid text NOT NULL, -- This is a permanent uuid that will stay constant regardless of succession version
     reference_type_id integer REFERENCES dictionaries.reference_types("id"), 
     authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
     enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
     reference jsonb NOT NULL, -- derived from JSON PBot node
     preceded_by_id integer REFERENCES refs("id"),
     succeeded_by_id integer REFERENCES refs("id"),
     removed boolean
);

-- from scale_data in original
CREATE TABLE timescales (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid integer NOT NULL,
    authorizer_person_id integer REFERENCES persons("id"),
    enterer_person_id integer REFERENCES persons("id"),
    name text NOT NULL,
    early_age numeric NOT NULL, -- equivalent to b_age/max_age
    late_age numeric NOT NULL, -- equivalent to t_age?min_age
    reference_id integer REFERENCES refs("id"),
    preceded_by integer REFERENCES timescales("id"),
    succeeded_by integer REFERENCES timescales("id")
    );

-- From interval_data in original
CREATE TABLE intervals (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid integer NOT NULL,
    authorizer_person_id integer REFERENCES persons("id"),
    enterer_person_id integer REFERENCES persons("id"),
    name text NOT NULL,
    abbreviation varchar(4),
    early_age numeric NOT NULL, -- equivalent to b_age
    late_age numeric NOT NULL, -- equivalent to t_age
    interval_type integer REFERENCES dictionaries.interval_types("id"),
    zone_type integer   REFERENCES dictionaries.zone_types("id"), -- only if interval_type is zone
    reference_id integer REFERENCES refs("id"),
    preceded_by integer REFERENCES intervals("id"),
    succeeded_by integer REFERENCES intervals("id")
    );

CREATE TABLE lookup.intervals_timescales (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interval_id integer REFERENCES intervals("id"),
    timescale_id integer REFERENCES timescales("id")
    );


 CREATE TABLE collections (
     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --This is the id of the collection record. It will be unique for each version of the collection.
     permid integer NOT NULL, -- This is a permanent uuid that will stay constant regardless of succession version
     authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
     enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
     collection jsonb NOT NULL, -- Collection json -- taken directly from PBot!!!
     reference_id integer REFERENCES refs("id") NOT NULL, -- A single refs is considered the "primary".
     early_age_id integer REFERENCES intervals("id") NOT NULL,
     late_age_id integer REFERENCES intervals("id") NOT NULL, -- just repeat early_age if only 1 age given
     preceded_by_id integer REFERENCES collections("id"),
     succeeded_by_id integer REFERENCES collections("id"),
     removed boolean
);

-- A lookup table for additional refs (called refs_secondary in original db)
CREATE TABLE additional_collection_refs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    collection_id integer REFERENCES collections("id"),
    reference_id integer REFERENCES refs("id")
);

CREATE TABLE schemas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid text NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    schema jsonb NOT NULL,
    reference_id integer REFERENCES refs("id") NOT NULL,
    preceded_by_id integer REFERENCES schemas("id"),
    succeeded_by_id integer REFERENCES schemas("id"),
    removed boolean
);

-- A lookup table for additional refs (called refs_secondary in original db)
CREATE TABLE additional_schema_refs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    schema_id integer REFERENCES schemas("id"),
    reference_id integer REFERENCES refs("id")
);


/*
CREATE TABLE schemas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid text NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    title text NOT NULL,
    year NUMERIC(4, 0) NOT NULL,
    purpose text NOT NULL, -- I don't know what is supposed to go here
    parts_preserved_id integer REFERENCES dictionaries.parts_preserved("id"),
    reference_id integer REFERENCES refs("id") NOT NULL,
    preceded_by_id integer REFERENCES schemas("id"),
    succeeded_by_id integer REFERENCES schemas("id")
);
*/
CREATE TABLE characters (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid text NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    parent_schema_id integer REFERENCES schemas("id"),
    parent_character_id integer REFERENCES characters("id"), -- optional
    name text NOT NULL,
    definition text,
    sort_order integer, -- Probably needs to be some constraint expression here that checks whether the order makes sense - i.e., for given parent, cannot be 2 if there is no 1
    preceded_by_id integer REFERENCES characters("id"),
    succeeded_by_id integer REFERENCES characters("id"),
    CONSTRAINT character_of CHECK (
        (parent_schema_id IS NOT NULL AND parent_character_id IS NULL) OR
        (parent_schema_id IS NULL AND parent_character_id IS NOT NULL)
    )
);

CREATE TABLE states (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid text NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    parent_character_id integer REFERENCES characters("id"), -- not optional
    parent_state_id integer REFERENCES states("id"), -- optional
    name text NOT NULL,
    definition text,
    sort_order integer, -- Probably needs to be some constraint expression here that checks whether the order makes sense - i.e., for given parent, cannot be 2 if there is no 1
    quantitative boolean NOT NULL DEFAULT FALSE,
    preceded_by_id integer REFERENCES states("id"),
    succeeded_by_id integer REFERENCES states("id"),
    CONSTRAINT state_of CHECK (
        (parent_character_id IS NOT NULL AND parent_state_id IS NULL) OR
        (parent_character_id IS NULL AND parent_state_id IS NOT NULL)
    )
);

-- This represents a significant change to authorities from v1.0, where it was
-- actually a table of taxonomic names and their associated authorities, rather than a table of authorities.
-- It is now exlusivley a table of authorities, and the taxonomic names themselves are stored in the taxa table.
CREATE TABLE authorities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid integer NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    parenthetical_citation text NOT NULL, -- e.g., Linnaeus 1766, L. R. Cox et al. 1969 (full citation, unstandardized format)
    authors jsonb, -- using same format as in refs, can be NULL
    year numeric(4,0) NOT NULL, -- year of authority
    authority_reference_id REFERENCES refs ("id"), -- see notes below
    reference_id integer REFERENCES refs("id") NOT NULL, -- see notes below
    preceded_by_id integer REFERENCES opinions("id"),
    succeeded_by_id integer REFERENCES opinions("id")
    );

-- The opinion system in PBDB is one of its most important and unique components
-- We need to preserve all of its current functionality while also introducing
-- Some more flexibility for PBot, namely the inclusion of more types of
-- taxonomic_relationship 
CREATE TABLE opinions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid integer NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    reference_id integer REFERENCES references("id") NOT NULL,
    taxon_id integer REFERENCES taxa("id") DEFERRABLE INITIALLY DEFERRED,
    synonym_taxon_id integer REFERENCES taxa("id"), -- can be NULL because it may not be a synonym
    objective_synonym boolean DEFAULT NULL, -- Must be TRUE or FALSE IF synonym_taxon_id is not NULL, otherwise can be NULL
    parent_taxon_id integer REFERENCES taxa('id'), -- can be NULL becuase sometimes is unknown
    form boolean, -- is it a form taxon
    extant boolean, -- is it an extant taxon
    invalid boolean, -- is it an invalid taxon (intead of boolean could have optinos like "invalid", "nomen dubium", "nomen nudum", etc.)
    opinion_confidence_id integer REFERENCES dictionaries.opinion_confidences("id"), -- changed from v1.0 basis field
    schema_id integer NOT NULL, -- There will need to be some blanket schema that essentially means Linnaean
    phylogentic_status_id integer REFERENCES dictionaries.phylogenetic_statuses("id"), -- enum values not added to dictionary yet
    spelling_type_id integer REFERENCES dictionaries.spelling_types("id"), -- enum values not added to dictionary yet... i don't know what was supposed to go here
    preceded_by_id integer REFERENCES opinions("id"),
    succeeded_by_id integer REFERENCES opinions("id")
    );

-- There is a order of operations collision here. The taxa table needs to reference opinions and authorities, 
-- but opinions also needs to reference taxa. 

-- One option to get around this is to create two taxa tables. Essentially a staging table that is used to create the opinions and authorities, 
-- and then a final taxa table that is built from authorities and opinions. This is similar to v1.0.

-- The other possibility is that we could set the foreign key constraint to be deferrable, 
-- which would allow us to insert into both tables without worrying about the order of operations.
-- I actually think this is the better option. It should only be necessary upon the original creation of a taxon, 
-- and then after that, the order of operations should be pretty straightforward.
CREATE TABLE taxa (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid integer NOT NULL, -- similar to orig_no from version 1
    parent_taxa_id integer REFERENCES taxa("id"), -- optional, but will be required for any taxon that is not a kingdom
    taxonomy_confidence_id integer REFERENCES dictionaries.taxonomy_confidences("id"), -- This is not entered by a user but is calculated by the system
    taxon_rank_id integer REFERENCES dictionaries.taxonomy_ranks("id") NOT NULL,
    taxon_name text NOT NULL, -- expression: "^(?:[A-Z][a-z]+)(?: \([A-Z][a-z]+\))?(?: [a-z]+){0,2}(?:.*?(?<!sp|spp|indet))$"
    common_name text,
    authority_id integer REFERENCES authorities("id"), -- see notes below
    authoritative_opinion_id REFERENCES opinions("id") DEFERRABLE INITIALLY DEFERRED, -- see notes below
    preceded_by_id integer REFERENCES taxa("id"),
    succeeded_by_id integer REFERENCES taxa("id")
    );

-- The most significant change here is that we essentially eliminate reidentification as a separate table
-- Instead, if something is a reidentification of a previous iteration, we link back to that prior occurrence

-- Also see the above change to the taxa table and the remove of orig_no
CREATE TABLE occurrences {
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid integer NOT NULL, 
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    taxon_id integer REFERENCES taxa("id") NOT NULL, -- the taxon in question
    reidentification_occurrence_id integer REFERENCES occurrences("id"),
    collection_id integer REFERENCES collections("id") NOT NULL, -- collection taxon belongs to
    reference_id integer REFERENCES references("id") NOT NULL,
    preceded_by_id integer REFERENCES occurrences("id"),
    succeeded_by_id integer REFERENCES occurrences("id")
    };

