CREATE SCHEMA dictionaries;
CREATE SCHEMA lookup;

CREATE TABLE dictionaries.genders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genders text NOT NULL
    );
INSERT INTO dictionaries.genders (genders) 
    VALUES ('Male'),('Female'),('Other'),('Anonymous');  

CREATE TABLE dictionaries.roles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role text NOT NULL,
    description text NOT NULL
    );
INSERT INTO dictionaries.roles (role,description) 
    VALUES ('Superadmin','Ability to directly modify database'),('Admin','Limited ability to modify database'),('Authorizer','Can approve data entries from Enterer role'),('Enterer','Can enter data into the database'),('Student', 'Can enter non-taxonomic data'),('Person','Has no stated privileges');

CREATE TABLE dictionaries.interval_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interval_type text NOT NULL
    );
INSERT INTO dictionaries.interval_types (interval_type) 
    VALUES ('Eon'),('Era'),('Period'),('Epoch'),('Age'),('Zone');

CREATE TABLE dictionaries.zone_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_type text NOT NULL
    );
INSERT INTO dictionaries.zone_types (zone_type) 
    VALUES ('trilobite'),('conodont'),('graptolite'),('foraminifera'),('calcareous nannofossil'),('palynomorph'),('mammalia'),('other');

CREATE TABLE dictionaries.taxonomy_ranks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_rank text NOT NULL
    );
INSERT INTO dictionaries.taxonomy_ranks (taxonomy_rank) 
    VALUES ('subspecies'),('species'),('subgenus'),('genus'),('subtribe'),('tribe'),('subfamily'),('family'),('superfamily'),('infraorder'),('suborder'),('superorder'),('infraclass'),('subclass'),('class'),('superclass'),('subphylum'),('phylum'),('superphylum'),('subkingdom'),('kingdom'),('superkingdom'),('unranked clade'),('unranked');

CREATE TABLE dictionaries.reference_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_type text
    );
INSERT INTO dictionaries.reference_types (reference_type) 
    VALUES ('journal article'),('standalone book'),('edited collection'),('article in edited collection'),('serial monograph'),('unpublished'),('other');

CREATE TABLE dictionaries.book_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_type text
    );
INSERT INTO dictionaries.book_types (book_type) 
    VALUES ('monograph'),('compendium'),('Ph.D. thesis'),('M.S. thesis'),('guidebook');

-- This is a required field for schemas in PBOT, but the current list on PBOT is only applicable to plants
-- Either this requirement needs to go away or a much more expansive and general list needs to be created.
CREATE TABLE dictionaries.parts_preserved (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
INSERT INTO dictionaries.parts_preserved (name)
    VALUES ('root'), ('shoot/axis/wood'), ('leaf'), ('pollen/spore'), ('inflorescence/flower'), ('infructescence/fruit'), ('ovuliferous (seed) cone'), ('staminate (pollen) cone'), ('seed'), ('cuticle'), ('other'), ('unknown');

CREATE TABLE dictionaries.notable_features (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
INSERT INTO dictionaries.notable_features (name)
    VALUES ('cuticle/epidermal features'), ('wood anatomy (secondary growth)'), ('internal anatomy'), ('trace fossils (e.g., insect damage)');

-- ============================================================
-- Entity versioning trigger system
-- Automatically swings FK references when a new entity version
-- is inserted and maintains the version chain.
-- ============================================================

-- Core function: finds all FKs pointing at target_table via pg_constraint
-- and updates them from old_id to new_id, excluding version-chain columns.
CREATE OR REPLACE FUNCTION swing_fks_to_new_version(
    target_table text,
    old_id integer,
    new_id integer
) RETURNS void AS $$
DECLARE
    fk record;
BEGIN
    FOR fk IN
        SELECT
            src_ns.nspname AS src_schema,
            src.relname    AS src_table,
            a_src.attname  AS src_column
        FROM pg_constraint con
        JOIN pg_class     src    ON con.conrelid  = src.oid
        JOIN pg_namespace src_ns ON src.relnamespace = src_ns.oid
        JOIN pg_class     tgt    ON con.confrelid = tgt.oid
        JOIN pg_attribute a_src
            ON  a_src.attrelid = con.conrelid
            AND a_src.attnum   = ANY(con.conkey)
        WHERE con.contype = 'f'
          AND tgt.relname = target_table
          AND a_src.attname NOT IN ('preceded_by_id', 'succeeded_by_id')
    LOOP
        EXECUTE format(
            'UPDATE %I.%I SET %I = $1 WHERE %I = $2',
            fk.src_schema, fk.src_table,
            fk.src_column, fk.src_column
        ) USING new_id, old_id;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- BEFORE INSERT trigger function: automatically determines lineage placement.
-- Finds the current head of the lineage (matching permid, succeeded_by_id IS NULL)
-- and sets preceded_by_id accordingly. Always clears succeeded_by_id.
CREATE OR REPLACE FUNCTION place_in_lineage()
RETURNS trigger AS $$
DECLARE
    head_id integer;
    head_count integer;
BEGIN
    -- Count existing lineage heads for this permid
    EXECUTE format(
        'SELECT count(*), max(id) FROM %I WHERE permid = $1 AND succeeded_by_id IS NULL',
        TG_TABLE_NAME
    ) USING NEW.permid INTO head_count, head_id;

    IF head_count > 1 THEN
        RAISE EXCEPTION 'Corrupted lineage: % heads found for permid % in table %',
            head_count, NEW.permid, TG_TABLE_NAME;
    END IF;

    -- Set preceded_by_id to the head (NULL if new lineage)
    IF head_count = 1 THEN
        NEW.preceded_by_id := head_id;
    ELSE
        NEW.preceded_by_id := NULL;
    END IF;

    -- Always clear succeeded_by_id on insert
    NEW.succeeded_by_id := NULL;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger function: swings FKs and sets succeeded_by_id on the old version.
-- Fires AFTER INSERT when preceded_by_id IS NOT NULL.
CREATE OR REPLACE FUNCTION handle_new_version()
RETURNS trigger AS $$
BEGIN
    -- Swing all external FK references from old version to new
    PERFORM swing_fks_to_new_version(TG_TABLE_NAME, NEW.preceded_by_id, NEW.id);

    -- Close out the old version
    EXECUTE format(
        'UPDATE %I SET succeeded_by_id = $1 WHERE id = $2',
        TG_TABLE_NAME
    ) USING NEW.id, NEW.preceded_by_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Helper: installs both version triggers on a given table.
CREATE OR REPLACE FUNCTION install_version_triggers(target_table text)
RETURNS void AS $$
BEGIN
    EXECUTE format(
        'CREATE TRIGGER a_place_in_lineage
         BEFORE INSERT ON %I
         FOR EACH ROW
         EXECUTE FUNCTION place_in_lineage()',
        target_table
    );
    EXECUTE format(
        'CREATE TRIGGER b_swing_fks_on_new_version
         AFTER INSERT ON %I
         FOR EACH ROW
         WHEN (NEW.preceded_by_id IS NOT NULL)
         EXECUTE FUNCTION handle_new_version()',
        target_table
    );
END;
$$ LANGUAGE plpgsql;

CREATE TABLE persons (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password text,
    role_id integer REFERENCES dictionaries.roles("id") NOT NULL,
    person jsonb NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- This requires a conditional expression, if the role_id is student or enterer, then it needs an authorizer or above
    active boolean,
    total_hours numeric
);
    
 CREATE TABLE refs (
     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --This is the id of the reference record. It will be unique for each version of the reference.
     permid text NOT NULL, -- This is a permanent uuid that will stay constant regardless of succession version
     reference_type_id integer REFERENCES dictionaries.reference_types("id"), 
     authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
     enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
     reference jsonb NOT NULL, -- derived from JSON PBot node
     preceded_by_id integer REFERENCES refs("id"),
     succeeded_by_id integer REFERENCES refs("id"),
     removed boolean
);
SELECT install_version_triggers('refs');

-- from scale_data in original
CREATE TABLE timescales (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid text NOT NULL,
    authorizer_person_id integer REFERENCES persons("id"),
    enterer_person_id integer REFERENCES persons("id"),
    name text NOT NULL,
    early_age numeric NOT NULL, -- equivalent to b_age/max_age
    late_age numeric NOT NULL, -- equivalent to t_age?min_age
    reference_id integer REFERENCES refs("id"),
    preceded_by_id integer REFERENCES timescales("id"),
    succeeded_by_id integer REFERENCES timescales("id")
);
SELECT install_version_triggers('timescales');

-- From interval_data in original
CREATE TABLE intervals (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid text NOT NULL,
    authorizer_person_id integer REFERENCES persons("id"),
    enterer_person_id integer REFERENCES persons("id"),
    name text NOT NULL,
    abbreviation varchar(4),
    early_age numeric NOT NULL, -- equivalent to b_age
    late_age numeric NOT NULL, -- equivalent to t_age
    interval_type integer REFERENCES dictionaries.interval_types("id"),
    zone_type integer   REFERENCES dictionaries.zone_types("id"), -- only if interval_type is zone
    reference_id integer REFERENCES refs("id"),
    preceded_by_id integer REFERENCES intervals("id"),
    succeeded_by_id integer REFERENCES intervals("id")
);
SELECT install_version_triggers('intervals');

CREATE TABLE lookup.intervals_timescales (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interval_id integer REFERENCES intervals("id"),
    timescale_id integer REFERENCES timescales("id")
    );


 CREATE TABLE collections (
     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --This is the id of the collection record. It will be unique for each version of the collection.
     permid text NOT NULL, -- This is a permanent uuid that will stay constant regardless of succession version
     authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
     enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
     collection jsonb NOT NULL, -- Collection json -- taken directly from PBot!!!
     reference_id integer REFERENCES refs("id") NOT NULL, -- A single refs is considered the "primary".
     early_age_id integer REFERENCES intervals("id") NOT NULL,
     late_age_id integer REFERENCES intervals("id") NOT NULL, -- just repeat early_age if only 1 age given
     preceded_by_id integer REFERENCES collections("id"),
     succeeded_by_id integer REFERENCES collections("id"),
     removed boolean
);
SELECT install_version_triggers('collections');

-- A lookup table for additional refs (called refs_secondary in original db)
CREATE TABLE additional_collection_refs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    collection_id integer REFERENCES collections("id"),
    reference_id integer REFERENCES refs("id")
);

CREATE TABLE schemas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid text NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    schema jsonb NOT NULL,
    reference_id integer REFERENCES refs("id") NOT NULL,
    preceded_by_id integer REFERENCES schemas("id"),
    succeeded_by_id integer REFERENCES schemas("id"),
    removed boolean
);
SELECT install_version_triggers('schemas');

-- A lookup table for additional refs (called refs_secondary in original db)
CREATE TABLE additional_schema_refs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    schema_id integer REFERENCES schemas("id"),
    reference_id integer REFERENCES refs("id")
);

CREATE TABLE characters (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid text NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    parent_schema_id integer REFERENCES schemas("id"),
    parent_character_id integer REFERENCES characters("id"), -- optional
    --name text NOT NULL,
    --definition text,
    sort_order integer, -- Probably needs to be some constraint expression here that checks whether the order makes sense - i.e., for given parent, cannot be 2 if there is no 1
    character jsonb NOT NULL,
    preceded_by_id integer REFERENCES characters("id"),
    succeeded_by_id integer REFERENCES characters("id"),
    removed boolean,
    CONSTRAINT character_of CHECK (
        (parent_schema_id IS NOT NULL AND parent_character_id IS NULL) OR
        (parent_schema_id IS NULL AND parent_character_id IS NOT NULL)
    )
);
SELECT install_version_triggers('characters');

CREATE TABLE states (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid text NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    parent_character_id integer REFERENCES characters("id"), -- not optional
    parent_state_id integer REFERENCES states("id"), -- optional
    --name text NOT NULL,
    --definition text,
    sort_order integer, -- Probably needs to be some constraint expression here that checks whether the order makes sense - i.e., for given parent, cannot be 2 if there is no 1
    state jsonb NOT NULL,
    quantitative boolean NOT NULL DEFAULT FALSE,
    preceded_by_id integer REFERENCES states("id"),
    succeeded_by_id integer REFERENCES states("id"),
    removed boolean,
    CONSTRAINT state_of CHECK (
        (parent_character_id IS NOT NULL AND parent_state_id IS NULL) OR
        (parent_character_id IS NULL AND parent_state_id IS NOT NULL)
    )
);
SELECT install_version_triggers('states');

-- This represents a significant change to authorities from v1.0, where it was
-- actually a table of taxonomic names and their associated authorities, rather than a table of authorities.
-- It is now exlusivley a table of authorities, and the taxonomic names themselves are stored in the taxa table.
CREATE TABLE authorities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid text NOT NULL, -- This is a permanent uuid that will stay constant regardless of succession version
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    authority jsonb NOT NULL, -- Defined in authority.schema.js
    reference_id integer REFERENCES refs("id") NOT NULL, -- see notes below
    preceded_by_id integer REFERENCES authorities("id"),
    succeeded_by_id integer REFERENCES authorities("id"),
    removed boolean
);
SELECT install_version_triggers('authorities');

-- For the taxa migration: each authority row carries every legacy taxon_no it
-- absorbed during dedup in authority->'legacyIDs'->'oldpbdbIDs' (jsonb array of
-- strings, sorted ASC). To resolve a legacy taxon_no → current authority.id,
-- add this index when the taxa migration runs:
--   CREATE INDEX authorities_oldpbdbids_gin
--     ON authorities USING gin ((authority->'legacyIDs'->'oldpbdbIDs') jsonb_path_ops);
--   -- lookup:
--   SELECT id FROM authorities
--    WHERE authority->'legacyIDs'->'oldpbdbIDs' ? '12345'
--      AND succeeded_by_id IS NULL;

-- This is what the new taxa table would look like
CREATE TABLE taxa (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid integer NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    name text NOT NULL, -- see special consideration below
    authority_id integer NOT NULL, -- the authority
    assignment_id integer REFERENCES assignment_opinions("id"), -- the "best" opinion for the parent taxon (e.g., family of genus)
    synonym_id integer REFERENCES synonymy_opinions("id"), -- the "best" opinion for SENIOR synonym (e.g., Brachiosaurus -> Giraffatitan)
    nomenclature_id integer REFERENCES nomenclature_opinions("id") NOT NULL, -- the "best" opinion for name/spelling
    description_id integer REFERENCES descriptions("id"), -- the "best" description. I am leaving this table undescribed for now because it touches on the PBOT system
    validity_id integer REFERENCES validity_opinions("id") NOT NULL, -- the "best" opinion on validity (nome nudem etc.)
    has_homonym boolean NOT NULL, -- see table notes below
    preceded_by_id integer REFERENCES taxa("id"),
    succeeded_by_id integer REFERENCES taxa("id")
    );

-- This is for table for opinions changing the taxonomic placement (e.g., family of genus) for a taxon
CREATE TABLE assignment_opinions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid integer NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    taxon_id integer REFERENCES taxa("id") NOT NULL,
    parent_taxon_id integer REFERENCES taxa("id") NOT NULL,
    evidence boolean NOT NULL, -- stated with or without evidence, see special consideration below
    reference_id integer REFERENCES refs("id"),
    preceded_by_id integer REFERENCES taxa("id"),
    succeeded_by_id integer REFERENCES taxa("id")
    );

-- This is for table for changing the name of a taxon
CREATE TABLE nomenclature_opinions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid integer NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    taxon_id integer REFERENCES taxa("id") NOT NULL,
    new_name text NOT NULL, -- this is the main purpose of this table
    rename_reason_id integer REFERENCES dictionaries.rename_reasons("id"), -- to a dictionaries table of reasons to change name
    evidence boolean NOT NULL, -- stated with or without evidence (I'm not sure this applies in this case)
    reference_id integer REFERENCES refs("id"),
    preceded_by_id integer REFERENCES taxa("id"),
    succeeded_by_id integer REFERENCES taxa("id")
    );

-- This is for table for asserting synonymy of a taxon
CREATE TABLE synonymy_opinions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid integer NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    taxon_id integer REFERENCES taxa("id") NOT NULL,
    senior_synonym_id integer REFERENCES taxa("id") NOT NULL,
    objective boolean NOT NULL, -- whether the synonymy is objective or subjective
    evidence boolean NOT NULL, -- stated with or without evidence, see special consideration below
    reference_id integer REFERENCES refs("id"),
    preceded_by_id integer REFERENCES taxa("id"),
    succeeded_by_id integer REFERENCES taxa("id")
    );

-- Table for describing validity
CREATE TABLE validity_opinions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid integer NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    taxon_id integer REFERENCES taxa("id") NOT NULL,
    taxonomic_validity_id integer REFERENCES dictionaries.taxonomic_validity("id") NOT NULL, -- e.g., nomen oblitum
    evidence boolean NOT NULL, -- stated with or without evidence, see special consideration below
    reference_id integer REFERENCES refs("id"),
    preceded_by_id integer REFERENCES taxa("id"),
    succeeded_by_id integer REFERENCES taxa("id")
    );

-- Lookup table for homonyms. Homonyms are treated differently because their existence is not necessarily derived from an 
-- opinion, but from a practical reality in our database. Furthermore, it is theoretically possible (though I know of no examples) 
-- for there to be more than two taxa sharing the same name, so a simple one-to-one child->parent style table structure like in -- the synonymy opinions tables would not work.
CREATE TABLE homonyms (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    younger_taxon_A_id integer REFERENCES taxa("id"), -- taxon with younger authority
    older_taxon_B_id integer REFERENCES taxa("id") -- taxon with older authority
    );

-- The most significant change here is that we essentially eliminate reidentification as a separate table
-- Instead, if something is a reidentification of a previous iteration, we link back to that prior occurrence

-- Also see the above change to the taxa table and the remove of orig_no
CREATE TABLE occurrences {
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid text NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    taxon_id integer REFERENCES taxa("id") NOT NULL, -- the taxon in question
    reidentification_occurrence_id integer REFERENCES occurrences("id"),
    collection_id integer REFERENCES collections("id") NOT NULL, -- collection taxon belongs to
    reference_id integer REFERENCES references("id") NOT NULL,
    preceded_by_id integer REFERENCES occurrences("id"),
    succeeded_by_id integer REFERENCES occurrences("id")
    };

