CREATE SCHEMA dictionaries;

CREATE TABLE dictionaries.genders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genders varchar NOT NULL
    );
INSERT INTO dictionaries.genders (genders) 
    VALUES ('Male'),('Female'),('Other'),('Anonymous');  

CREATE TABLE dictionaries.roles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role varchar NOT NULL,
    description varchar NOT NULL
    );
INSERT INTO dictionaries.roles (role,description) 
    VALUES ('Superadmin','Ability to directly modify database'),('Admin','Limited ability to modify database'),('Authorizer','Can approve data entries from Enterer role'),('Enterer','Can enter data into the database'),('Student', 'Can enter non-taxonomic data'),('Person','Has no stated privileges');

CREATE TABLE dictionaries.countries (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abbreviation varchar NOT NULL,
    full_name varchar NOT NULL
    );
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(1, 'AF', 'Afghanistan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(2, 'AX', 'Oland Islands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(3, 'AL', 'Albania') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(4, 'DZ', 'Algeria') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(5, 'AS', 'American Samoa') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(6, 'AD', 'Andorra') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(7, 'AO', 'Angola') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(8, 'AI', 'Anguilla') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(9, 'AQ', 'Antarctica') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(10, 'AG', 'Antigua and Barbuda') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(11, 'AR', 'Argentina') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(12, 'AM', 'Armenia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(13, 'AW', 'Aruba') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(14, 'AU', 'Australia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(15, 'AT', 'Austria') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(16, 'AZ', 'Azerbaijan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(17, 'BS', 'Bahamas') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(18, 'BH', 'Bahrain') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(19, 'BD', 'Bangladesh') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(20, 'BB', 'Barbados') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(21, 'BY', 'Belarus') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(22, 'BE', 'Belgium') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(23, 'BZ', 'Belize') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(24, 'BJ', 'Benin') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(25, 'BM', 'Bermuda') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(26, 'BT', 'Bhutan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(27, 'BO', 'Bolivia, Plurinational State of') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(28, 'BQ', 'Bonaire, Sint Eustatius and Saba') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(29, 'BA', 'Bosnia and Herzegovina') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(30, 'BW', 'Botswana') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(31, 'BV', 'Bouvet Island') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(32, 'BR', 'Brazil') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(33, 'IO', 'British Indian Ocean Territory') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(34, 'BN', 'Brunei Darussalam') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(35, 'BG', 'Bulgaria') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(36, 'BF', 'Burkina Faso') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(37, 'BI', 'Burundi') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(38, 'KH', 'Cambodia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(39, 'CM', 'Cameroon') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(40, 'CA', 'Canada') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(41, 'CV', 'Cape Verde') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(42, 'KY', 'Cayman Islands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(43, 'CF', 'Central African Republic') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(44, 'TD', 'Chad') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(45, 'CL', 'Chile') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(46, 'CN', 'China') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(47, 'CX', 'Christmas Island') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(48, 'CC', 'Cocos (Keeling) Islands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(49, 'CO', 'Colombia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(50, 'KM', 'Comoros') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(51, 'CG', 'Congo') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(52, 'CD', 'Congo, the Democratic Republic of the') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(53, 'CK', 'Cook Islands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(54, 'CR', 'Costa Rica') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(55, 'CI', 'C√¥te d''Ivoire') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(56, 'HR', 'Croatia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(57, 'CU', 'Cuba') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(58, 'CW', 'Cura√ßao') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(59, 'CY', 'Cyprus') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(60, 'CZ', 'Czech Republic') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(61, 'DK', 'Denmark') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(62, 'DJ', 'Djibouti') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(63, 'DM', 'Dominica') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(64, 'DO', 'Dominican Republic') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(65, 'EC', 'Ecuador') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(66, 'EG', 'Egypt') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(67, 'SV', 'El Salvador') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(68, 'GQ', 'Equatorial Guinea') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(69, 'ER', 'Eritrea') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(70, 'EE', 'Estonia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(71, 'ET', 'Ethiopia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(72, 'FK', 'Falkland Islands (Malvinas)') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(73, 'FO', 'Faroe Islands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(74, 'FJ', 'Fiji') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(75, 'FI', 'Finland') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(76, 'FR', 'France') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(77, 'GF', 'French Guiana') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(78, 'PF', 'French Polynesia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(79, 'TF', 'French Southern Territories') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(80, 'GA', 'Gabon') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(81, 'GM', 'Gambia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(82, 'GE', 'Georgia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(83, 'DE', 'Germany') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(84, 'GH', 'Ghana') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(85, 'GI', 'Gibraltar') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(86, 'GR', 'Greece') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(87, 'GL', 'Greenland') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(88, 'GD', 'Grenada') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(89, 'GP', 'Guadeloupe') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(90, 'GU', 'Guam') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(91, 'GT', 'Guatemala') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(92, 'GG', 'Guernsey') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(93, 'GN', 'Guinea') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(94, 'GW', 'Guinea-Bissau') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(95, 'GY', 'Guyana') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(96, 'HT', 'Haiti') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(97, 'HM', 'Heard Island and McDonald Islands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(98, 'VA', 'Holy See (Vatican City State)') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(99, 'HN', 'Honduras') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(100, 'HK', 'Hong Kong') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(101, 'HU', 'Hungary') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(102, 'IS', 'Iceland') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(103, 'IN', 'India') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(104, 'ID', 'Indonesia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(105, 'IR', 'Iran, Islamic Republic of') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(106, 'IQ', 'Iraq') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(107, 'IE', 'Ireland') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(108, 'IM', 'Isle of Man') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(109, 'IL', 'Israel') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(110, 'IT', 'Italy') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(111, 'JM', 'Jamaica') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(112, 'JP', 'Japan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(113, 'JE', 'Jersey') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(114, 'JO', 'Jordan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(115, 'KZ', 'Kazakhstan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(116, 'KE', 'Kenya') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(117, 'KI', 'Kiribati') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(118, 'KP', 'Korea, Democratic People''s Republic of') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(119, 'KR', 'Korea, Republic of') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(120, 'KW', 'Kuwait') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(121, 'KG', 'Kyrgyzstan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(122, 'LA', 'Lao People''s Democratic Republic') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(123, 'LV', 'Latvia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(124, 'LB', 'Lebanon') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(125, 'LS', 'Lesotho') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(126, 'LR', 'Liberia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(127, 'LY', 'Libya') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(128, 'LI', 'Liechtenstein') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(129, 'LT', 'Lithuania') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(130, 'LU', 'Luxembourg') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(131, 'MO', 'Macao') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(132, 'MK', 'Macedonia, the Former Yugoslav Republic of') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(133, 'MG', 'Madagascar') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(134, 'MW', 'Malawi') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(135, 'MY', 'Malaysia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(136, 'MV', 'Maldives') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(137, 'ML', 'Mali') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(138, 'MT', 'Malta') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(139, 'MH', 'Marshall Islands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(140, 'MQ', 'Martinique') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(141, 'MR', 'Mauritania') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(142, 'MU', 'Mauritius') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(143, 'YT', 'Mayotte') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(144, 'MX', 'Mexico') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(145, 'FM', 'Micronesia, Federated States of') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(146, 'MD', 'Moldova, Republic of') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(147, 'MC', 'Monaco') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(148, 'MN', 'Mongolia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(149, 'ME', 'Montenegro') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(150, 'MS', 'Montserrat') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(151, 'MA', 'Morocco') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(152, 'MZ', 'Mozambique') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(153, 'MM', 'Myanmar') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(154, 'NA', 'Namibia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(155, 'NR', 'Nauru') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(156, 'NP', 'Nepal') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(157, 'NL', 'Netherlands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(158, 'NC', 'New Caledonia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(159, 'NZ', 'New Zealand') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(160, 'NI', 'Nicaragua') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(161, 'NE', 'Niger') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(162, 'NG', 'Nigeria') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(163, 'NU', 'Niue') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(164, 'NF', 'Norfolk Island') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(165, 'MP', 'Northern Mariana Islands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(166, 'NO', 'Norway') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(167, 'OM', 'Oman') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(168, 'PK', 'Pakistan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(169, 'PW', 'Palau') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(170, 'PS', 'Palestine, State of') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(171, 'PA', 'Panama') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(172, 'PG', 'Papua New Guinea') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(173, 'PY', 'Paraguay') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(174, 'PE', 'Peru') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(175, 'PH', 'Philippines') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(176, 'PN', 'Pitcairn') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(177, 'PL', 'Poland') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(178, 'PT', 'Portugal') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(179, 'PR', 'Puerto Rico') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(180, 'QA', 'Qatar') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(181, 'RE', 'Reunion') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(182, 'RO', 'Romania') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(183, 'RU', 'Russian Federation') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(184, 'RW', 'Rwanda') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(185, 'BL', 'Saint Barth√©lemy') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(186, 'SH', 'Saint Helena, Ascension and Tristan da Cunha') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(187, 'KN', 'Saint Kitts and Nevis') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(188, 'LC', 'Saint Lucia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(189, 'MF', 'Saint Martin (French part)') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(190, 'PM', 'Saint Pierre and Miquelon') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(191, 'VC', 'Saint Vincent and the Grenadines') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(192, 'WS', 'Samoa') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(193, 'SM', 'San Marino') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(194, 'ST', 'Sao Tome and Principe') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(195, 'SA', 'Saudi Arabia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(196, 'SN', 'Senegal') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(197, 'RS', 'Serbia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(198, 'SC', 'Seychelles') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(199, 'SL', 'Sierra Leone') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(200, 'SG', 'Singapore') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(201, 'SX', 'Sint Maarten (Dutch part)') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(202, 'SK', 'Slovakia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(203, 'SI', 'Slovenia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(204, 'SB', 'Solomon Islands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(205, 'SO', 'Somalia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(206, 'ZA', 'South Africa') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(207, 'GS', 'South Georgia and the South Sandwich Islands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(208, 'SS', 'South Sudan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(209, 'ES', 'Spain') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(210, 'LK', 'Sri Lanka') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(211, 'SD', 'Sudan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(212, 'SR', 'Suriname') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(213, 'SJ', 'Svalbard and Jan Mayen') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(214, 'SZ', 'Swaziland') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(215, 'SE', 'Sweden') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(216, 'CH', 'Switzerland') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(217, 'SY', 'Syrian Arab Republic') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(218, 'TW', 'Taiwan, Province of China') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(219, 'TJ', 'Tajikistan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(220, 'TZ', 'Tanzania, United Republic of') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(221, 'TH', 'Thailand') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(222, 'TL', 'Timor-Leste') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(223, 'TG', 'Togo') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(224, 'TK', 'Tokelau') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(225, 'TO', 'Tonga') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(226, 'TT', 'Trinidad and Tobago') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(227, 'TN', 'Tunisia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(228, 'TR', 'Turkey') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(229, 'TM', 'Turkmenistan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(230, 'TC', 'Turks and Caicos Islands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(231, 'TV', 'Tuvalu') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(232, 'UG', 'Uganda') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(233, 'UA', 'Ukraine') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(234, 'AE', 'United Arab Emirates') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(235, 'GB', 'United Kingdom') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(236, 'US', 'United States') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(237, 'UM', 'United States Minor Outlying Islands') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(238, 'UY', 'Uruguay') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(239, 'UZ', 'Uzbekistan') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(240, 'VU', 'Vanuatu') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(241, 'VE', 'Venezuela, Bolivarian Republic of') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(242, 'VN', 'Viet Nam') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(243, 'VG', 'Virgin Islands, British') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(244, 'VI', 'Virgin Islands, U.S.') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(245, 'WF', 'Wallis and Futuna') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(246, 'EH', 'Western Sahara') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(247, 'YE', 'Yemen') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(248, 'ZM', 'Zambia') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(249, 'ZW', 'Zimbabwe') RETURNING "id", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("id", "abbreviation", "full_name") VALUES(250, 'XX', 'Unknown') RETURNING "id", "abbreviation", "full_name";

CREATE TABLE dictionaries.taxonomy_ranks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_rank varchar NOT NULL
    );
INSERT INTO dictionaries.taxonomy_ranks (taxonomy_rank) 
    VALUES ('subspecies'),('species'),('subgenus'),('genus'),('subtribe'),('tribe'),('subfamily'),('family'),('superfamily'),('infraorder'),('suborder'),('superorder'),('infraclass'),('subclass'),('class'),('superclass'),('subphylum'),('phylum'),('superphylum'),('subkingdom'),('kingdom'),('superkingdom'),('unranked clade'),('unranked');

CREATE TABLE dictionaries.reference_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_type varchar
    );
INSERT INTO dictionaries.reference_types (reference_type) 
    VALUES ('journal article'),('standalone book'),('edited collection'),('article in edited collection'),('serial monograph'),('unpublished'),('other');

CREATE TABLE dictionaries.book_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_type varchar
    );
INSERT INTO dictionaries.book_types (book_type) 
    VALUES ('monograph'),('compendium'),('Ph.D. thesis'),('M.S. thesis'),('guidebook');

CREATE TABLE dictionaries.taxonomy_relationships (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_relationship varchar
    );
INSERT INTO dictionaries.taxonomy_relationships (taxonomy_relationship)
    VALUES ('belongs to'),('subjective synonym of'),('objective synonym of'),('invalid subgroup of'),('misspelling of'),('replaced by'),('nomen dubium'),('nomen nudum'),('nomen oblitum'),('nomen vanum');

CREATE TABLE dictionaries.taxonomy_confidences (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_confidence varchar,
    taxonomy_confidence_definition varchar
    );
INSERT INTO dictionaries.taxonomy_confidences (taxonomy_confidence,taxonomy_confidence_definition)
    VALUES ('accepted','An accepted name is a valid name that is not a junior synonym.'),('superseded','A valid name that is a junior synonym.'),('operational','An informal name that can confidently be used as an operational taxonomic unit.'),('tentative','An informal name that is not recommended for general use as an operational taxonomic unit.'),('undocumented','A presumably valid formal name but it is missing a valid authority entry in the database.'),('invalid','A name that is formally considered invalid.');

CREATE TABLE persons (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    given_name varchar NOT NULL,
    family_name varchar NOT NULL,
    middle varchar,
    email varchar,
    password varchar,
    orcid varchar,
    role_id integer REFERENCES dictionaries.roles("id") NOT NULL,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- This requires a conditional expression, if the role_id is student or enterer, then it needs an authorizer or above
    gender_id integer REFERENCES dictionaries.genders("id") NOT NULL,
    country_id integer REFERENCES dictionaries.countries("id") NOT NULL,
    institution varchar,
    active boolean,
    total_hours numeric
    );
    
 CREATE TABLE references (
     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --This is the id of the reference record. It will be unique for each version of the reference.
     permid varchar NOT NULL, -- This is a permanent uuid that will stay constant regardless of succession version
     reference_type_id integer REFERENCES dictionaries.reference_types("id"), 
     authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
     enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
     reference jsonb, -- derived from JSON PBot node
     preceded_by_id integer REFERENCES references("id"),
     succeeded_by_id integer REFERENCES references("id"),
     removed boolean
     );

 CREATE TABLE collections (
     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --This is the id of the collection record. It will be unique for each version of the collection.
     permid integer NOT NULL, -- This is a permanent uuid that will stay constant regardless of succession version
     authorizer_person_id integer REFERENCES person("id") NOT NULL, -- Whoever was the authorizer of the enterer
     enterer_person_id integer REFERENCES person("id") NOT NULL, -- Whoever made the entry or edit
     collection jsonb, -- Collection json -- taken directly from PBot!!!
     reference_id integer REFERENCES references("id") NOT NULL, -- A single refs is considered the "primary". 
     preceded_by_id integer REFERENCES collections("id"),
     succeeded_by_id integer REFERENCES collections("id"),
     removed boolean
     );

-- A lookup table for additional refs (called refs_secondary in original db)
CREATE TABLE additional_reference (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES person("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES person("id") NOT NULL, -- Whoever made the entry or edit
    collection_id integer REFERENCES collection("id"),
    reference_id integer REFERENCES references("id")
    );

-- I want to move type-specimens out to a separate table, if not multiple tables.
CREATE TABLE authorities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    taxonomy_confidence_id integer REFERENCES dictionaries.taxonomy_confidences("id"),
    taxon_rank_id integer REFERENCES dictionaries.taxon_ranks('id') NOT NULL,
    taxon_name varchar NOT NULL, -- expression: "^(?:[A-Z][a-z]+)(?: \([A-Z][a-z]+\))?(?: [a-z]+){0,2}(?:.*?(?<!sp|spp|indet))$"
    common_name varchar,
    authority_citation varchar NOT NULL, -- I need to think more deeply about ref_is_authority workflow
    reference_id integer REFERENCES references('id') NOT NULL
    );

-- The opinion system in PBDB is one of its most important and unique components
-- We need to preserve all of its current functionality while also introducing
-- Some more flexibility for PBot, namely the inclusion of more types of
-- taxonomic_relationship 
CREATE TABLE opinion (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    reference_id integer REFERENCES references("id") NOT NULL,
    child_authority_id integer REFERENCES authorities("id") NOT NULL,
    taxonomy_relationship_id integer REFERENCES dictionaries.taxonomy_relationships("id"),
    parent_authority_id integer REFERENCES authorities('id') NOT NULL,
    basis_id integer REFERENCES dictionaries.basises("id"), -- enum values not added to dictionary yet, also basises sounds dumb
    phylogentic_status_id integer REFERENCES dictionaries.phylogenetic_statuses("id") -- enum values not added to dictionary yet
    spelling_type_id integer REFERENCES dictionaries.spelling_types("id") -- enum values not added to dictionary yet
    preceded_by_id integer REFERENCES opinions("id"),
    succeeded_by_id integer REFERENCES opinions("id")
    );

-- The taxon table needs to be updated upon changes to the authorities and/or opinion
-- tables
CREATE TABLE taxa (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_confidence_id integer REFERENCES dictionaries.taxonomy_confidences("id"),
    taxonomy_rank_id integer REFERENCES dictionaries.taxonomy_ranks("id")
    );

-- The most significant change here is that we essentially eliminate reidentification as a separate table
-- Instead, if something is a reidentification of a previous iteration, we link back to that prior occurrence
CREATE TABLE occurrences {
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid integer NOT NULL, 
    authorizer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_person_id integer REFERENCES persons("id") NOT NULL, -- Whoever made the entry or edit
    taxon_id integer REFERENCES taxa("id") NOT NULL, -- the taxon in question
    reidentification_occurrence_id integer REFERENCES occurrences("id"),
    collection_id integer REFERENCES collections("id") NOT NULL, -- collection taxon belongs to
    reference_id integer REFERENCES references("id") NOT NULL,
    preceded_by_id integer REFERENCES opinions("id"),
    succeeded_by_id integer REFERENCES opinions("id")
    };
