-- ============================================================================
-- taxa & opinions — DRAFT DDL
-- ============================================================================
--
-- STATUS: draft for discussion, NOT committed schema. Nothing here has been
-- run. Fold into postgresql/create_new.sql by hand once settled.
--
-- Supersedes the taxa/rank_opinions/assignment_opinions/rename_opinions/
-- homonyms block currently in create_new.sql, which predates the design work
-- in docs/classic-taxa-opinions.md §9.
--
-- Design rationale: docs/classic-taxa-opinions.md
--   §9.5   truth vs. materialization; the three layers
--   §9.5.2.1  why Layer 1 is NOT versioned
--   §9.6   column vocabulary (succession / concept / classification)
--   §9.7   performance seams that must not be foreclosed
--   §10    legacy field disposition + migration strategy
--
-- Two conventions inherited from create_new.sql:
--   * permid uuid + CHECK ((get_byte(uuid_send(permid), 6) >> 4) = 7).
--     CHECK only, matching create_new.sql as it stands: permids are minted by
--     the application. The PG16-compatible get_byte form may become
--     uuid_extract_version(permid) = 7, and gain a DEFAULT uuidv7(), once the
--     database is on PG18 (see openspec/specs/permid-uuidv7/spec.md).
--   * SELECT install_version_triggers('t') installs place_in_lineage() /
--     handle_new_version() AND a partial index t_permid_head_idx on
--     (permid) WHERE succeeded_by_id IS NULL. Do not hand-create that index.
--
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS ltree;


-- ============================================================================
-- DICTIONARIES
-- ----------------------------------------------------------------------------
-- Expressed as ALTER/INSERT against the existing create_new.sql dictionaries;
-- fold into the original CREATE statements when merging.
-- ============================================================================

-- dictionaries.taxonomy_ranks has two problems:
--   1. 'order' is missing entirely (the list jumps infraorder → suborder →
--      superorder). The legacy MySQL enum has 26 values; this list has 24.
--   2. derive() must enforce Classic's rule that a containing taxon's rank is
--      strictly higher (Opinion.pm:1163). Relying on id order breaks as soon as
--      'unranked clade'/'unranked' sit at the end of the list, so rank ordering
--      needs to be explicit rather than positional. NULL height = unranked,
--      which is the correct semantics: no comparison is possible.
ALTER TABLE dictionaries.taxonomy_ranks ADD COLUMN height integer;

INSERT INTO dictionaries.taxonomy_ranks (taxonomy_rank) VALUES ('order');

UPDATE dictionaries.taxonomy_ranks t SET height = v.height
FROM (VALUES
    ('subspecies', 10), ('species', 20), ('subgenus', 30), ('genus', 40),
    ('subtribe', 50), ('tribe', 60), ('subfamily', 70), ('family', 80),
    ('superfamily', 90), ('infraorder', 100), ('suborder', 110), ('order', 120),
    ('superorder', 130), ('infraclass', 140), ('subclass', 150), ('class', 160),
    ('superclass', 170), ('subphylum', 180), ('phylum', 190),
    ('superphylum', 200), ('subkingdom', 210), ('kingdom', 220),
    ('superkingdom', 230)
    -- 'unranked clade' and 'unranked' deliberately keep height NULL
) AS v(taxonomy_rank, height)
WHERE t.taxonomy_rank = v.taxonomy_rank;


-- NOTE: there is deliberately NO dictionary table for evidence. Legacy
-- `opinions.basis` is a 5-value enum, but pbdb2 collapses it to a boolean:
-- `stated with evidence` → true, everything else (including NULL) → false.
-- Each opinion table therefore carries a plain `evidence boolean NOT NULL`,
-- as create_new.sql already had. The 30% of legacy opinions with
-- `basis IS NULL` are resolved against the reference's basis AT MIGRATION
-- TIME, not at read time — pbdb2's `refs` has no basis field at all, so
-- there is nothing for derive() to fall back to. See §10.5.
--
-- derive()'s winner selection is consequently:
--
--     ORDER BY subject_permid,
--              synthesized ASC,   -- real opinions always outrank synthesized
--              evidence DESC,     -- true before false
--              COALESCE(pubyr, reference publication year) DESC,
--              id DESC
--
-- `synthesized` is the first key because a boolean leaves no room below
-- `false` for the migration floor the old reliability dictionary provided.
-- Making it a separate key is the better factoring anyway: "is this a real
-- published statement?" and "how good is its evidence?" are independent
-- questions, and encoding the floor as a reliability level conflated them.


-- Sources taxa.nomenclatural_status_id. These are the legacy `opinions.status`
-- values that are neither an assignment nor a name change — 12,806 rows that
-- have no home in the other opinion tables.
CREATE TABLE dictionaries.nomenclatural_statuses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status text NOT NULL,
    targeted boolean NOT NULL   -- whether target_permid is required
);
INSERT INTO dictionaries.nomenclatural_statuses (status, targeted) VALUES
    ('nomen dubium',        false),   -- legacy: 8,208
    ('nomen nudum',         false),   -- legacy: 2,533
    ('nomen vanum',         false),   -- legacy:   569
    ('nomen oblitum',       false),   -- legacy:    76
    ('invalid subgroup of', true);    -- legacy: 1,420


-- dictionaries.namechange_reasons must cover legacy `spelling_reason` ∪ the
-- synonymy half of legacy `status`. Existing rows (after the create_new.sql
-- fix): original, misspelling, assignment, reranked, code, junior synonym.
--
-- RESOLVED (open call A): 'nomen oblitum' has been removed from
-- namechange_reasons and lives only in dictionaries.nomenclatural_statuses
-- above. It is a validity/priority status — the name itself is unaltered — not
-- a spelling act, so it never belonged among the name-change reasons. The row
-- was deleted from the create_new.sql seed directly.
--
-- merges_concept marks the reasons whose senior_permid target causes two
-- name-lineages to collapse into one concept during derive()'s union-find.
ALTER TABLE dictionaries.namechange_reasons
    ADD COLUMN merges_concept boolean NOT NULL DEFAULT false;

INSERT INTO dictionaries.namechange_reasons (reason, description, merges_concept) VALUES
    ('recombination',        'Species moved to a different genus',            false),
    ('correction',           'Grammatical/orthographic correction',           false),
    ('subjective synonym',   'Junior subjective synonym of another taxon',    true),
    ('objective synonym',    'Junior objective synonym of another taxon',     true),
    ('replaced by',          'Name replaced (e.g. homonymy)',                 true);

UPDATE dictionaries.namechange_reasons
   SET merges_concept = true
 WHERE reason IN ('misspelling', 'junior synonym');


-- ============================================================================
-- LAYER 1 — ASSERTIONS (input to derive())
-- ----------------------------------------------------------------------------
-- Append-only and immutable. Deliberately NOT versioned: see §9.5.2.1.
-- Succession chains record changes of belief; `taxa` has beliefs, opinions
-- have only transcription accuracy. Versioning here would add a third temporal
-- axis on top of valid-time (pubyr) and transaction-time (ledger order),
-- degrading the §9.5.5 invariant to derive(all, as_of) ≡ heads(as_of).
--
-- Consequently these tables carry NO permid, NO preceded_by_id/succeeded_by_id
-- and NO install_version_triggers(). Data-entry corrections are errata, not
-- history, and are handled by the audit columns below. derive() reads
-- `WHERE removed IS NOT TRUE` with no head predicate anywhere.
--
-- All *_permid columns are name-lineage pointers, NOT SQL foreign keys. There
-- is deliberately no permid registry table (§9.5.1); integrity is by
-- construction and re-checked by the derive(all) ≡ heads invariant.
--
-- A permid is MINTED by a name_opinions row with reason = 'original'. That row
-- is the birth certificate; nothing else creates a taxon.
-- ============================================================================

-- Name, spelling, synonymy — and the naming act itself.
--
-- 'original' is a reason value rather than a separate table so that competing
-- claims about what the original combination was become an ordinary ranking
-- contest instead of a constraint violation. Classic needed a bad-data branch
-- in getOriginalCombination (TaxonInfo.pm:2043) precisely because it had no
-- way to express two candidate originals.
CREATE TABLE name_opinions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL,
    enterer_person_id integer REFERENCES persons("id") NOT NULL,

    subject_permid uuid NOT NULL,          -- the name-lineage this is about
    new_name text NOT NULL,
    reason_id integer REFERENCES dictionaries.namechange_reasons("id") NOT NULL,
    senior_permid uuid,                    -- lateral target; required when reason.merges_concept
    objective boolean,                     -- synonymy only: objective vs subjective

    -- Present only on reason = 'original': the naming act's own provenance.
    -- Legacy authorities.pages/figures record where in the reference the name
    -- was erected — per-name data that could not survive the authorities
    -- dedup (517,287 legacy rows → 161,768 authority rows).
    authority_id bigint REFERENCES authorities("id"),
    pages text,
    figures text,

    reference_id bigint REFERENCES refs("id") NOT NULL,
    pubyr integer,       -- second-hand: the attributed year, overriding the reference's
    attribution jsonb,   -- second-hand: WHO, authors only; payloadSchemas/opinionAttribution.schema.js
    evidence boolean NOT NULL,   -- stated with evidence (true) vs. everything else
    synthesized boolean NOT NULL DEFAULT false,  -- constructed by migration, not published

    modifier_person_id integer REFERENCES persons("id"),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    modified_at timestamptz,
    removed boolean,

    CONSTRAINT name_opinion_not_self CHECK (subject_permid IS DISTINCT FROM senior_permid)
);

CREATE TABLE rank_opinions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL,
    enterer_person_id integer REFERENCES persons("id") NOT NULL,

    subject_permid uuid NOT NULL,
    rank_id integer REFERENCES dictionaries.taxonomy_ranks("id") NOT NULL,

    reference_id bigint REFERENCES refs("id") NOT NULL,
    pubyr integer,       -- second-hand: the attributed year, overriding the reference's
    attribution jsonb,   -- second-hand: WHO, authors only; payloadSchemas/opinionAttribution.schema.js
    evidence boolean NOT NULL,   -- stated with evidence (true) vs. everything else
    synthesized boolean NOT NULL DEFAULT false,

    modifier_person_id integer REFERENCES persons("id"),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    modified_at timestamptz,
    removed boolean
);

-- Classification / containment. NOT "parent": rank containment is not
-- evolutionary ancestry (§9.6.1). A family contains a genus; it is not its
-- ancestor.
CREATE TABLE assignment_opinions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL,
    enterer_person_id integer REFERENCES persons("id") NOT NULL,

    subject_permid uuid NOT NULL,
    containing_permid uuid NOT NULL,
    questioned boolean NOT NULL DEFAULT false,   -- incertae sedis

    reference_id bigint REFERENCES refs("id") NOT NULL,
    pubyr integer,       -- second-hand: the attributed year, overriding the reference's
    attribution jsonb,   -- second-hand: WHO, authors only; payloadSchemas/opinionAttribution.schema.js
    evidence boolean NOT NULL,   -- stated with evidence (true) vs. everything else
    synthesized boolean NOT NULL DEFAULT false,

    modifier_person_id integer REFERENCES persons("id"),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    modified_at timestamptz,
    removed boolean,

    CONSTRAINT assignment_not_self CHECK (subject_permid <> containing_permid)
);

-- Nomenclatural validity. A nomen dubium is NOT a name change (the name is
-- unaltered) and NOT an assignment (nothing moves), so it fits neither of the
-- tables above — hence its own. This is also what replaces the second job of
-- the old `taxa.accepted` boolean; see §10.4.
--
-- Tree-affecting: sinking a genus as nomen dubium changes what its species can
-- be assigned to, so dependency_closure must chase these.
CREATE TABLE validity_opinions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL,
    enterer_person_id integer REFERENCES persons("id") NOT NULL,

    subject_permid uuid NOT NULL,
    status_id integer REFERENCES dictionaries.nomenclatural_statuses("id") NOT NULL,
    target_permid uuid,          -- required iff the status is `targeted`

    reference_id bigint REFERENCES refs("id") NOT NULL,
    pubyr integer,       -- second-hand: the attributed year, overriding the reference's
    attribution jsonb,   -- second-hand: WHO, authors only; payloadSchemas/opinionAttribution.schema.js
    evidence boolean NOT NULL,   -- stated with evidence (true) vs. everything else
    synthesized boolean NOT NULL DEFAULT false,

    modifier_person_id integer REFERENCES persons("id"),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    modified_at timestamptz,
    removed boolean
);

-- ---------------------------------------------------------------------------
-- Attribute opinions: winner-selection only, NO tree propagation.
-- dependency_closure ignores these entirely — an edit here dirties exactly one
-- permid and never ripples laterally or downward.
-- ---------------------------------------------------------------------------

-- Type material. Modelled as an opinion because type designation is a dated,
-- contestable published act: the original description fixes a type, but a
-- later paper designates a lectotype or neotype when the original material is
-- lost or ambiguous. Absorbs the legacy authorities type block.
--
-- OPEN: one row asserts the whole type block, so a later lectotype
-- designation that says nothing about type locality would drop the locality on
-- winning. May need splitting per dimension. See §10.6.
CREATE TABLE type_opinions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL,
    enterer_person_id integer REFERENCES persons("id") NOT NULL,

    subject_permid uuid NOT NULL,
    type_taxon_permid uuid,      -- type species / type genus
    type_specimen text,
    museum text,
    catalog_number text,
    body_part text,
    part_details text,
    type_locality_collection_id bigint REFERENCES collections("id"),

    reference_id bigint REFERENCES refs("id") NOT NULL,
    pubyr integer,       -- second-hand: the attributed year, overriding the reference's
    attribution jsonb,   -- second-hand: WHO, authors only; payloadSchemas/opinionAttribution.schema.js
    evidence boolean NOT NULL,   -- stated with evidence (true) vs. everything else
    synthesized boolean NOT NULL DEFAULT false,

    modifier_person_id integer REFERENCES persons("id"),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    modified_at timestamptz,
    removed boolean
);

-- Biological traits: legacy authorities.extant, preservation, form_taxon.
--
-- PLACEHOLDER. This is the boundary where PBOT's description system takes
-- over, so the payload is jsonb rather than typed columns pending that
-- decision. This table may end up being — or being absorbed by — the
-- `descriptions` table referenced but left undefined in create_new.sql.
-- See §10.6.
CREATE TABLE trait_opinions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_person_id integer REFERENCES persons("id") NOT NULL,
    enterer_person_id integer REFERENCES persons("id") NOT NULL,

    subject_permid uuid NOT NULL,
    traits jsonb NOT NULL,       -- { extant, preservation, formTaxon, ... }

    reference_id bigint REFERENCES refs("id") NOT NULL,
    pubyr integer,       -- second-hand: the attributed year, overriding the reference's
    attribution jsonb,   -- second-hand: WHO, authors only; payloadSchemas/opinionAttribution.schema.js
    evidence boolean NOT NULL,   -- stated with evidence (true) vs. everything else
    synthesized boolean NOT NULL DEFAULT false,

    modifier_person_id integer REFERENCES persons("id"),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    modified_at timestamptz,
    removed boolean
);


-- ============================================================================
-- LAYER 2 — THE DERIVATION
-- ----------------------------------------------------------------------------
-- No DDL. Layer 2 is taxonomy.derive(permids), a pure function over Layer 1
-- and the single definition of truth (§9.5.2). It is called by both the hot
-- path (statement trigger over dependency_closure) and the cold path
-- (rebuild() / migration / CI), which is what makes the invariant
--
--     derive(all) ≡ { current ledger heads }
--
-- checkable. This heading is a deliberate placeholder so the gap between
-- Layer 1 and Layer 3 reads as intentional.
-- ============================================================================


-- ============================================================================
-- LAYER 3 — THE LEDGER (materialized output of derive())
-- ============================================================================

-- Pure materialized output. Nothing here is hand-entered, which is why there
-- is no authorizer_person_id / enterer_person_id: every value traces to a
-- winning opinion, and attributing a derived row to a person would be a lie.
--
-- Rebuilding this table from Layer 1 must be lossless. Anything that cannot be
-- reconstructed by derive() does not belong here — see "OUTSIDE THE STACK".
CREATE TABLE taxa (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid uuid NOT NULL CHECK ((get_byte(uuid_send(permid), 6) >> 4) = 7),  -- name-lineage identity; replaces legacy orig_no

    name text NOT NULL,                    -- currently accepted spelling
    rank_id integer REFERENCES dictionaries.taxonomy_ranks("id"),
    authority_id bigint REFERENCES authorities("id"),

    -- Concept membership (synonymy). This permid IS the accepted name of its
    -- concept  <=>  concept_permid = permid. That equality is what replaces
    -- the old `accepted` boolean's first job; no column is needed for it.
    concept_permid uuid NOT NULL,

    -- Classification. Adjacency is PRIMARY and classification_path is an
    -- explicitly derived materialization that can be reshaped or dropped as a
    -- cache change (§9.7.4 invariant 4). Making the path primary would be the
    -- nested-set trap again.
    containing_concept_permid uuid,        -- NULL = root
    classification_path ltree,             -- ltree of concept permids, root → node

    -- Nomenclatural validity: NULL = valid. Replaces the old `accepted`
    -- boolean's second job, as an enum rather than a boolean, because
    -- "invalid" and "is a junior synonym" are independent conditions.
    nomenclatural_status_id integer REFERENCES dictionaries.nomenclatural_statuses("id"),

    -- Provenance: which opinion won each dimension. Auditability was one of
    -- Classic's genuine virtues (§7) and is preserved explicitly here.
    winning_name_opinion_id       bigint REFERENCES name_opinions("id"),
    winning_rank_opinion_id       bigint REFERENCES rank_opinions("id"),
    winning_assignment_opinion_id bigint REFERENCES assignment_opinions("id"),
    winning_validity_opinion_id   bigint REFERENCES validity_opinions("id"),
    winning_type_opinion_id       bigint REFERENCES type_opinions("id"),
    winning_trait_opinion_id      bigint REFERENCES trait_opinions("id"),

    preceded_by_id bigint REFERENCES taxa("id"),
    succeeded_by_id bigint REFERENCES taxa("id"),
    removed boolean,
    created_at timestamptz DEFAULT NOW()
);
SELECT install_version_triggers('taxa');

-- taxa_permid_head_idx is created by install_version_triggers(). These are the
-- additional head-only indexes derive() and the read path need.
CREATE INDEX taxa_head_concept_idx
    ON taxa (concept_permid) WHERE succeeded_by_id IS NULL;
CREATE INDEX taxa_head_containing_idx
    ON taxa (containing_concept_permid) WHERE succeeded_by_id IS NULL;
CREATE INDEX taxa_head_path_idx
    ON taxa USING gist (classification_path) WHERE succeeded_by_id IS NULL;
CREATE INDEX taxa_head_name_idx
    ON taxa (name) WHERE succeeded_by_id IS NULL;


-- ============================================================================
-- OUTSIDE THE STACK — non-derived data
-- ----------------------------------------------------------------------------
-- Neither input to derive() nor output of it. Hand-entered, never
-- reconstructed by rebuild(), and invisible to dependency_closure. These sit
-- beside the Layer 1/2/3 stack, not above it.
-- ============================================================================

-- Curatorial annotation has no opinion behind it — nobody published a paper
-- asserting a comment. It therefore CANNOT live in `taxa`: a rebuild() would
-- blank it. Versioned, because unlike an opinion this is authored content
-- whose edits are genuine changes of content.
CREATE TABLE taxon_annotations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid uuid NOT NULL CHECK ((get_byte(uuid_send(permid), 6) >> 4) = 7),
    authorizer_person_id integer REFERENCES persons("id") NOT NULL,
    enterer_person_id integer REFERENCES persons("id") NOT NULL,

    subject_permid uuid NOT NULL,          -- the taxon being annotated
    common_name text,
    comments text,
    discussion text,
    discussed_by_reference_id bigint REFERENCES refs("id"),

    preceded_by_id bigint REFERENCES taxon_annotations("id"),
    succeeded_by_id bigint REFERENCES taxon_annotations("id"),
    removed boolean,
    created_at timestamptz DEFAULT NOW()
);
SELECT install_version_triggers('taxon_annotations');

CREATE INDEX taxon_annotations_head_subject_idx
    ON taxon_annotations (subject_permid) WHERE succeeded_by_id IS NULL;

-- Homonymy is a fact about our data, not a published assertion: the legacy
-- `opinions.status` enum has ten values and none of them is 'homonym of'.
-- Grouped rather than pairwise so that n > 2 homonyms are representable
-- (n rows sharing a homonym_group_id), which an A/B pair table could not do.
--
-- Note there is no has_homonym flag on `taxa`: that would make a derived table
-- depend on a non-opinion source. Read-path LEFT JOIN instead.
CREATE TABLE homonyms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    homonym_group_id bigint NOT NULL,
    permid uuid NOT NULL,
    created_at timestamptz DEFAULT NOW(),
    UNIQUE (homonym_group_id, permid)
);
CREATE INDEX homonyms_permid_idx ON homonyms (permid);


-- ============================================================================
-- LAYER 1 INDEXES
-- ----------------------------------------------------------------------------
-- derive() gathers opinions by subject, and dependency_closure walks the
-- lateral (concept) and downward (containment) edges.
-- ============================================================================

CREATE INDEX name_opinions_subject_idx       ON name_opinions (subject_permid);
CREATE INDEX name_opinions_senior_idx        ON name_opinions (senior_permid);
CREATE INDEX rank_opinions_subject_idx       ON rank_opinions (subject_permid);
CREATE INDEX assignment_opinions_subject_idx ON assignment_opinions (subject_permid);
CREATE INDEX assignment_opinions_containing_idx ON assignment_opinions (containing_permid);
CREATE INDEX validity_opinions_subject_idx   ON validity_opinions (subject_permid);
CREATE INDEX type_opinions_subject_idx       ON type_opinions (subject_permid);
CREATE INDEX trait_opinions_subject_idx      ON trait_opinions (subject_permid);


-- ============================================================================
-- OPEN QUESTIONS (see §10.6)
-- ============================================================================
--
-- 1. trait_opinions: jsonb payload vs typed columns — blocked on the PBOT
--    descriptions decision. May not survive as its own table.
--
-- 2. type_opinions: one row per whole type block, or split per dimension so a
--    lectotype designation cannot silently drop the type locality?
--
-- 3. RESOLVED (open call A): 'nomen oblitum' is a nomenclatural validity/
--    priority status, not a name-change reason. Removed from
--    namechange_reasons (create_new.sql); it lives only in
--    dictionaries.nomenclatural_statuses.
--
-- 4. RESOLVED (open call B, §10.5): rank fan-out — emit one rank_opinion per
--    legacy opinion (~998K), rank taken from that opinion's child_spelling_no.
--    Faithful to Classic (rank comes from the winning spelling's authorities
--    row) and ~1M rows is trivial for Postgres. The lean ~425K variant is
--    rejected: it would let a 1990 rank change outrank a 2010 usage that
--    re-used the older spelling.
--
-- 5. RESOLVED. Both `attribution` and `pubyr` STAY (decision, 2026-07-27).
--    create_new.sql's opinion tables carry neither, holding only `evidence`
--    and `reference_id`; the draft's addition of both is confirmed, and the
--    "reference_id is sufficient, drop them" direction is rejected, not
--    merely deferred. Do not reopen.
--
--    attribution no longer borrows authority.schema.js. That
--    schema describes an authority record — it carries legacyIDs.oldpbdbIDs and
--    publishedInReference (meaningless on an opinion) and sets
--    unevaluatedProperties: false, so it cannot be reused without them.
--    attribution now has its own authors-only schema,
--    payloadSchemas/opinionAttribution.schema.js, and the duplicated `year`
--    field is gone: the year lives ONLY in the `pubyr` column, because
--    derive() sorts on it. The rule is that every derive() input is a typed,
--    constrained, indexable column and everything else is payload.
--
--    `pubyr` is integer, not text: it is a sort key, and text ordering matches
--    numeric ordering only while every value is exactly 4 digits. Verified
--    safe to cast — all 128,722 populated legacy values are 4-digit numerics,
--    zero non-conforming.
--
--    DECIDED (2026-07-27): derive() ranks on `pubyr` — it is a derive() INPUT,
--    not payload, so a second-hand opinion competes at the year it was stated
--    rather than the year it was reported. This is Classic's behaviour and it
--    is what the ORDER BY at the top of this file already encodes.
--
--    Note the fallback is load-bearing, not incidental: `pubyr` is populated
--    only for the second-hand case (869,843 of 998,565 legacy opinions leave
--    it empty), so the key is COALESCE(pubyr, reference publication year) —
--    pubyr takes precedence WHERE PRESENT, and the reference's year carries
--    the other 87%. `pubyr` alone would leave most opinions undated.
--
-- 6. No permid registry table means nothing prevents an opinion referencing a
--    permid that was never minted. Accepted by decision (§9.5.1); the
--    derive(all) invariant is the backstop. Revisit only if it bites.
