-- reset-opinions.sql
-- Drops and recreates the opinions output tables + the three dictionaries the
-- opinions migration reads, from postgresql/create_new.sql (the schema authority).
-- DDL blocks are copied verbatim from create_new.sql so they cannot drift from the
-- authority. Originally emitted by scratch-build-reset.mjs, which is no longer in
-- the repository -- maintain the DDL below by copying from create_new.sql by hand.
--
-- KEEP (not touched): persons, refs, authorities -- the already-migrated input layer.
--
-- AFTER running this you MUST re-mint the name_opinions ROOT rows (edge_class='root')
-- from authorities BEFORE running the opinions migration -- it reads those permids.
-- Both steps, in order, with their preconditions checked:
--
--   psql ... -f src/opinions-migration/tests/reset-opinions.sql
--   node src/run-migrations.js --only authority-opinions   -- re-mints the ROOT rows
--   node src/run-migrations.js --only opinions
--
-- This file clears exactly the tables those two steps require to be empty, so the
-- runner's preconditions verify the re-mint happened rather than trusting this note.

BEGIN;

-- ============================================================================
-- 1. DROP (children first: opinion tables reference the dictionaries below)
-- ============================================================================
DROP TABLE IF EXISTS name_opinions;
DROP TABLE IF EXISTS assignment_opinions;
DROP TABLE IF EXISTS validity_opinions;
DROP TABLE IF EXISTS dictionaries.namechange_reasons;
DROP TABLE IF EXISTS dictionaries.nomenclatural_statuses;
DROP TABLE IF EXISTS dictionaries.taxonomy_ranks;

-- ============================================================================
-- 2. RECREATE dictionaries (parents first)
-- ============================================================================

-- dictionaries.taxonomy_ranks -----------------------------------------------
CREATE TABLE dictionaries.taxonomy_ranks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_rank text NOT NULL,
    height integer
    );
INSERT INTO dictionaries.taxonomy_ranks (taxonomy_rank, height)
    VALUES ('subspecies', 10), ('species', 20), ('subgenus', 30), ('genus', 40),
           ('subtribe', 50), ('tribe', 60), ('subfamily', 70), ('family', 80),
           ('superfamily', 90), ('infraorder', 100), ('suborder', 110), ('order', 120),
           ('superorder', 130), ('infraclass', 140), ('subclass', 150), ('class', 160),
           ('superclass', 170), ('subphylum', 180), ('phylum', 190), ('superphylum', 200),
           ('subkingdom', 210), ('kingdom', 220), ('superkingdom', 230),
           ('unranked clade', NULL), ('unranked', NULL);

-- dictionaries.namechange_reasons -------------------------------------------
CREATE TABLE dictionaries.namechange_reasons (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason text NOT NULL,
    description text,
    edge_class text NOT NULL,
    never_accepted boolean NOT NULL DEFAULT false,
    CONSTRAINT namechange_reasons_edge_class_check CHECK (edge_class IN ('root', 'name', 'concept')),
    -- composite unique key referenced by name_opinions' (reason_id, edge_class) FK:
    CONSTRAINT namechange_reasons_id_edge_class_key UNIQUE (id, edge_class)
);
INSERT INTO dictionaries.namechange_reasons (reason, description, edge_class, never_accepted)
    VALUES
        ('original',         'The original published name',                                        'root',    false),
        ('correction',       'Grammatical/orthographic correction (incl. ICZN-code-mandated changes)', 'name',    false),
        ('reranked',         'The taxon has changed rank (from genus to family, implies re-assignment)', 'name',    false),
        ('recombination',    'Species combined with a different genus',                            'name',    false),
        ('assignment',       'The assignment of the taxon changed (e.g., new genus for species)',  'name',    false),
        ('misspelling',      'The taxon''s name was misspelled (noticed incidentally, e.g. while entering a belongs-to opinion; legacy spelling_reason=''misspelling'')', 'name',    true),
        ('historical misspelling', 'A formally published opinion whose entire content is the claim that this name is a misspelling (legacy status=''misspelling of'')', 'name',    true),
        ('junior synonym',   'The taxon is a junior synonym of another taxon',                     'concept', false),
        ('replaced by',      'Name replaced (e.g. homonymy)',                                      'concept', false),
        ('invalid subgroup', 'The taxon is an invalid subgroup, folded into the target''s concept', 'concept', false),
        ('nomen oblitum',    'A forgotten senior name, folded into the protected junior name''s concept', 'concept', false);

-- dictionaries.nomenclatural_statuses ---------------------------------------
CREATE TABLE dictionaries.nomenclatural_statuses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status text NOT NULL,
    bars_candidacy boolean NOT NULL DEFAULT false  -- true only for nomen nudum
);
INSERT INTO dictionaries.nomenclatural_statuses (status, bars_candidacy) VALUES
    ('nomen dubium',  false),
    ('nomen nudum',   true),
    ('nomen vanum',   false),
    ('nomen oblitum', false);

-- ============================================================================
-- 3. RECREATE opinion output tables
-- ============================================================================

-- name_opinions --------------------------------------------------------------
CREATE TABLE name_opinions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid uuid NOT NULL CHECK ((get_byte(uuid_send(permid), 6) >> 4) = 7),  -- opinion identity across transcription corrections
    authorizer_person_id integer REFERENCES persons("id") NOT NULL,
    enterer_person_id integer REFERENCES persons("id") NOT NULL,
    oldpbdb_taxon_no integer,

    subject_permid uuid NOT NULL,          -- the name-as-spelled this opinion is about
    target_permid uuid,                    -- what subject defers to; NULL only for edge_class 'root' ('original')
    reason_id integer NOT NULL,            -- FK is composite with edge_class, below
    edge_class text NOT NULL,              -- pinned copy of the reason's edge_class (Way 2 / A1). Lets the
                                           -- shape CHECK run as a plain same-row CHECK; the composite FK
                                           -- below guarantees it equals the dictionary's value for reason_id.
    negates boolean NOT NULL DEFAULT false, -- flips the polarity of `reason` rather than naming its own
                                           -- reason: `reason = 'misspelling', negates = true` reads as
                                           -- "not a misspelling of [target]," not "misspelling." NOT
                                           -- pinned to the dictionary (unlike edge_class) — polarity is a
                                           -- fact about this opinion, not a permanent property of the
                                           -- reason token. `edge_class = 'root'` rows are never negated
                                           -- (see name_opinion_shape). See taxa-opinions spec, "An opinion
                                           -- can assert the negation of a name or concept relationship."
    objective boolean,                     -- 'junior synonym' edges only: objective (true) vs subjective (false).
                                           -- SOLE carrier of the split (D7): no separate synonym reason tokens.

    -- IMMUTABLE identity of subject_permid, populated ONLY on the minting row.
    -- NULL on non-minting (concept-class) edges. rank_id here is where legacy
    -- authorities.taxon_rank lands. There is no separate rank_opinions table.
    new_name text,
    rank_id integer REFERENCES dictionaries.taxonomy_ranks("id"),

    -- Present on the 'original' minting row: the naming act's own provenance.
    authority_id bigint REFERENCES authorities("id"),

    reference_id bigint REFERENCES refs("id") NOT NULL,
    publication_year integer,       -- second-hand: the attributed year, overriding the reference's
    attribution jsonb,   -- second-hand: WHO, authors only; payloadSchemas/opinionAttribution.schema.js
    evidence boolean NOT NULL,   -- stated with evidence (true) vs. everything else

    created_at timestamptz NOT NULL DEFAULT NOW(),
    removed boolean,
    preceded_by_id bigint REFERENCES name_opinions("id"),
    succeeded_by_id bigint REFERENCES name_opinions("id"),

    CONSTRAINT name_opinion_not_self CHECK (subject_permid IS DISTINCT FROM target_permid),

    -- Way 2 (A1 / §10.6 D9): pin (reason_id, edge_class) to the dictionary's composite
    -- unique key, so the row's edge_class is provably the reason's and cannot drift.
    FOREIGN KEY (reason_id, edge_class)
        REFERENCES dictionaries.namechange_reasons (id, edge_class),

    -- THE MINTING SHAPE, a plain same-row CHECK because edge_class is on the row.
    -- Identity (new_name, rank_id) is set IFF edge_class = 'root': a permid's name
    -- and rank are minted once, on its root row (from authorities); name and
    -- concept edges assert relationships between permids whose identities already
    -- live on their own root rows, so they carry a target and NO identity.
    -- (Ledger model — mapping doc §3.2, 2026-08-17.)
    --   'root'    ('original')    ⇒ no target; mints identity  (new_name, rank_id set)
    --   'name'    (new spelling)  ⇒ target set; NO identity     (new_name, rank_id NULL)
    --   'concept' (synonymy edge) ⇒ target set; NO identity     (new_name, rank_id NULL)
    CONSTRAINT name_opinion_shape CHECK (
           (edge_class = 'root'    AND target_permid IS NULL     AND new_name IS NOT NULL AND rank_id IS NOT NULL AND negates = false)
        OR (edge_class = 'name'    AND target_permid IS NOT NULL AND new_name IS NULL     AND rank_id IS NULL)
        OR (edge_class = 'concept' AND target_permid IS NOT NULL AND new_name IS NULL     AND rank_id IS NULL)
    )
    -- RESIDUAL (not covered here): "objective NOT NULL iff reason = 'junior synonym'"
    -- needs reason-token granularity edge_class lacks; left to the write path + a
    -- derive(all) assertion (§10.6 D9 Residual).
);

-- assignment_opinions --------------------------------------------------------
CREATE TABLE assignment_opinions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid uuid NOT NULL CHECK ((get_byte(uuid_send(permid), 6) >> 4) = 7),  -- opinion identity across transcription corrections
    authorizer_person_id integer REFERENCES persons("id") NOT NULL,
    enterer_person_id integer REFERENCES persons("id") NOT NULL,

    subject_permid uuid NOT NULL,
    containing_permid uuid,        -- NULL = Classic asserted no containing taxon (see above)
    questioned boolean NOT NULL DEFAULT false,   -- incertae sedis

    reference_id bigint REFERENCES refs("id") NOT NULL,
    publication_year integer,       -- second-hand: the attributed year, overriding the reference's
    attribution jsonb,   -- second-hand: WHO, authors only; payloadSchemas/opinionAttribution.schema.js
    evidence boolean NOT NULL,   -- stated with evidence (true) vs. everything else

    created_at timestamptz NOT NULL DEFAULT NOW(),
    removed boolean,
    preceded_by_id bigint REFERENCES assignment_opinions("id"),
    succeeded_by_id bigint REFERENCES assignment_opinions("id"),

    CONSTRAINT assignment_not_self CHECK (subject_permid <> containing_permid)
);

-- validity_opinions ----------------------------------------------------------
CREATE TABLE validity_opinions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permid uuid NOT NULL CHECK ((get_byte(uuid_send(permid), 6) >> 4) = 7),  -- opinion identity across transcription corrections
    authorizer_person_id integer REFERENCES persons("id") NOT NULL,
    enterer_person_id integer REFERENCES persons("id") NOT NULL,

    subject_permid uuid NOT NULL,
    nomenclatural_status_id integer NOT NULL REFERENCES dictionaries.nomenclatural_statuses("id"),

    reference_id bigint REFERENCES refs("id") NOT NULL,
    publication_year integer,       -- second-hand: the attributed year, overriding the reference's
    attribution jsonb,   -- second-hand: WHO, authors only; payloadSchemas/opinionAttribution.schema.js
    evidence boolean NOT NULL,   -- stated with evidence (true) vs. everything else

    created_at timestamptz NOT NULL DEFAULT NOW(),
    removed boolean,
    preceded_by_id bigint REFERENCES validity_opinions("id"),
    succeeded_by_id bigint REFERENCES validity_opinions("id")
);

-- ============================================================================
-- 4. RECREATE indexes (head-lookup indexes are NOT optional -- see comments)
-- ============================================================================
CREATE INDEX name_opinions_subject_idx          ON name_opinions (subject_permid)          WHERE succeeded_by_id IS NULL;
CREATE INDEX name_opinions_target_idx           ON name_opinions (target_permid)           WHERE succeeded_by_id IS NULL;
CREATE INDEX assignment_opinions_subject_idx    ON assignment_opinions (subject_permid)    WHERE succeeded_by_id IS NULL;
CREATE INDEX assignment_opinions_containing_idx ON assignment_opinions (containing_permid) WHERE succeeded_by_id IS NULL;
CREATE INDEX validity_opinions_subject_idx      ON validity_opinions (subject_permid)      WHERE succeeded_by_id IS NULL;

-- Head lookup by permid. Elsewhere install_version_triggers() creates this; because
-- the opinion tables deliberately skip it (§9.5.2.1), these are created BY HAND and
-- are NOT optional — the write path resolves "current version of this opinion"
-- through them (the lookup whose absence degraded the collections migration to O(n²)).
CREATE INDEX name_opinions_permid_head_idx       ON name_opinions (permid)       WHERE succeeded_by_id IS NULL;
CREATE INDEX assignment_opinions_permid_head_idx ON assignment_opinions (permid) WHERE succeeded_by_id IS NULL;
CREATE INDEX validity_opinions_permid_head_idx   ON validity_opinions (permid)   WHERE succeeded_by_id IS NULL;

COMMIT;
